#!/bin/sh

# Copyright (C) 2023-2025 Ilias Koukovinis <ilias.koukovinis@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

echo "\033[0m" # Clear any styling present from preinst

# Debut and configure Nginx to automatically initialize on system startup
sudo systemctl enable --now nginx

if ! grep -q 'ermis' /etc/passwd; then
    echo "\033[1mCreating ermis user\033[0m"
    sudo adduser ermis
    sudo usermod -aG sudo ermis

    sudo chown ermis /var/ermis-server
    sudo chown ermis /opt/ermis-server
    sudo chown ermis /etc/nginx

    sudo chown -R ermis:ermis /var/ermis-server
    sudo chown -R ermis:ermis /opt/ermis-server
    sudo chown -R ermis:ermis /etc/nginx

    sudo chmod 700 /var/ermis-server
    sudo chmod 700 /opt/ermis-server
    sudo chmod 700 /etc/nginx
else
    echo "\033[1m'ermis' user detected; skipping user creation process.\033[0m"
fi

echo

echo "\033[1mYou can find thorough instructions on configuring the server in the README FILE at /opt/ermis-server/. In addition, you can visit the Ermis Wiki directly here: https://github.com/Koukobin/Ermis/wiki/.\033[0m"
echo "\033[1;31;4mKeep in mind that ermis-server by itself doesn't prevent DDoS attacks; I recommend using something like IPTables to configure the IP packet filter rules of the Linux kernel firewall in conjunction with Fail2ban which automatically blocks IP addresses exhibiting suspicious patterns of behaviour. Alternatively, you could use a VPN such as Tailscale.\033[0m"
echo "\033[1mFor better monitoring and performance tracking, consider integrating a monitoring toolkit - like Prometheus (the monitoring system; not the one from Greek mythology) - to gather metrics from the server, such as resource usage, latency, and response times.\033[0m"

