#!/bin/sh

sudo apt update
sudo apt-get upgrade

# Install Nginx, debut and configure to automatically initialize on system startup
sudo apt install nginx-full
sudo systemctl enable --now nginx

# Install Coturn (TURN/STUN server for WebRTC)
sudo apt install coturn

echo

echo "\033[1mYou can find thorough instructions on configuring the server in the README FILE at /opt/ermis-server/. In addition, you can visit the Ermis Wiki directly here: https://github.com/Koukobin/Ermis/wiki/\033[0m"
echo "\033[1;31;4mKeep in mind that ermis-server by itself doesn't prevent DDoS attacks; I recommend using something like IPTables to configure the IP packet filter rules of the Linux kernel firewall in conjunction with Fail2ban which automatically blocks IP addresses exhibiting suspicious patterns of behaviour. Alternatively, you could use a VPN such as Tailscale.\033[0m"
echo "\033[1mFor better monitoring and performance tracking, consider integrating a monitoring toolkit - like Prometheus (the monitoring system; not the one from Greek mythology) - to gather metrics from the server, such as resource usage, latency, and response times.\033[0m"

