services:
  cert-init:
    image: alpine
    volumes:
      - ./certs:/certs:ro
      - ermis_certs:/ermis_certs
      - pg_certs:/pg_certs
      - nginx_certs:/nginx_certs
    command: >
      sh -c "
        cp /certs/ca.crt /ermis_certs/ && chown 1567:1567 /ermis_certs/ca.crt
        cp /certs/ca.crt /pg_certs/ && chown 999:999 /pg_certs/ca.crt
        cp /certs/ca.crt /nginx_certs/ && chown 101:101 /nginx_certs/ca.crt
        echo ""
        cp /certs/ca.key /ermis_certs/ && chown 1567:1567 /ermis_certs/ca.key
        cp /certs/ca.key /pg_certs/ && chown 999:999 /pg_certs/ca.key
        cp /certs/ca.key /nginx_certs/ && chown 101:101 /nginx_certs/ca.key
        echo ""
        cp /certs/keystore.jks /ermis_certs/ && chown 1567:1567 /ermis_certs/keystore.jks
        cp /certs/keystore.jks /pg_certs/ && chown 999:999 /pg_certs/keystore.jks
        cp /certs/keystore.jks /nginx_certs/ && chown 101:101 /nginx_certs/keystore.jks
        echo ""
        cp /certs/server.crt /ermis_certs/ && chown 1567:1567 /ermis_certs/server.crt
        cp /certs/server.crt /pg_certs/ && chown 999:999 /pg_certs/server.crt
        cp /certs/server.crt /nginx_certs/ && chown 101:101 /nginx_certs/server.crt
        echo ""
        cp /certs/server.p12 /ermis_certs/ && chown 1567:1567 /ermis_certs/server.p12
        cp /certs/server.p12 /pg_certs/ && chown 999:999 /pg_certs/server.p12
        cp /certs/server.p12 /nginx_certs/ && chown 101:101 /nginx_certs/server.p12
        echo ""
        cp /certs/server_full.pem /ermis_certs/ && chown 1567:1567 /ermis_certs/server_full.pem
        cp /certs/server_full.pem /pg_certs/ && chown 999:999 /pg_certs/server_full.pem
        cp /certs/server_full.pem /nginx_certs/ && chown 101:101 /nginx_certs/server_full.pem
        echo ""
        cp /certs/server.key /ermis_certs/ && chown 1567:1567 /ermis_certs/server.key
        cp /certs/server.key /pg_certs/ && chown 999:999 /pg_certs/server.key
        cp /certs/server.key /nginx_certs/ && chown 101:101 /nginx_certs/server.key
        echo ""
        cp /certs/server_plain.key /ermis_certs/ && chown 1567:1567 /ermis_certs/server_plain.key
        cp /certs/server_plain.key /pg_certs/ && chown 999:999 /pg_certs/server_plain.key
        cp /certs/server_plain.key /nginx_certs/ && chown 101:101 /nginx_certs/server_plain.key
      "
    restart: "no"

  ermis-server:
    image: koukobin/ermis-server:${SERVER_VERSION}
    networks:
      - ermis-net
    secrets:
      - db_user_password
      - keystore_password
      - emailer_password
    ports:
      - "5551:5551"
    volumes:
      - ./ermis-configs:/etc/ermis-server/configs
      - ermis_certs:/etc/ermis-server/certs:ro
      - ./secrets:/run/secrets/ermis-server.service:ro
      - ermis-user-files:/var/lib/ermis-server
      - ./web_assets:/var/ermis-server/
    depends_on:
      postgres:
        condition: service_healthy
      cert-init:
        condition: service_completed_successfully
#    restart: unless-stopped

  postgres:
    image: postgres:18.3-bookworm
    depends_on: [cert-init]
    networks:
      - ermis-net
    secrets:
      - db_user_password
    environment:
      POSTGRES_DB: ermis_database
      POSTGRES_USER: ermis_admin
      POSTGRES_PASSWORD_FILE: /run/secrets/db_user_password
    volumes:
      - ermis-postgres-data:/var/lib/postgresql/main
      - pg_certs:/var/lib/postgresql/certs:ro
    command: >
      postgres
        -c ssl=on
        -c ssl_cert_file=/var/lib/postgresql/certs/server.crt
        -c ssl_key_file=/var/lib/postgresql/certs/server_plain.key
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ermis_admin -d ermis_database"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:1.30-alpine
    networks:
      - ermis-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ermis-configs/nginx/:/etc/nginx/:ro
      - ./web_assets:/var/ermis-server/
      - nginx_certs:/etc/ermis-server/certs:ro
    depends_on:
      - ermis-server
      - cert-init
    restart: unless-stopped

networks:
  ermis-net:
    driver: bridge

secrets:
  db_user_password:
    file: ./secrets/db_user_password
  keystore_password:
    file: ./secrets/keystore_password
  emailer_password:
    file: ./secrets/emailer_password

volumes:
  ermis-user-files:
  ermis-postgres-data:
  ermis_certs:
  pg_certs:
  nginx_certs:
