services:
  ermis-server:
    build:
      context: ..
      dockerfile: ErmisServer/Docker/Dockerfile
    networks:
      - ermis-net
    secrets:
      - db_user_password
      - keystore_password
      - emailer_password
    ports:
      - "5551:5551"
    volumes:
      - ./ermis-configs:/etc/ermis-server/configs
      - ./certs:/etc/ermis-server/certs:ro
      - ./secrets:/run/secrets/ermis-server.service:ro
      - ermis-user-files:/var/lib/ermis-server
      - ermis-static-assets:/var/ermis-server/
    depends_on:
      postgres:
        condition: service_healthy
#    restart: unless-stopped

  postgres:
    image: postgres:18.3-bookworm
    networks:
      - ermis-net
    secrets:
      - db_user_password
    environment:
      POSTGRES_DB: ermis_database
      POSTGRES_USER: ermis_admin
      POSTGRES_PASSWORD_FILE: /run/secrets/db_user_password
    volumes:
      - ermis-postgres-data:/var/lib/postgresql/main
      - ./certs/server.crt:/var/lib/postgresql/certs/server.crt:ro
      - ./certs/server_plain.key:/var/lib/postgresql/certs/server.key:ro
    command: >
      postgres
        -c ssl=on
        -c ssl_cert_file=/var/lib/postgresql/certs/server.crt
        -c ssl_key_file=/var/lib/postgresql/certs/server.key
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ermis_admin -d ermis_database"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:1.30-alpine
    networks:
      - ermis-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ermis-configs/nginx/:/etc/nginx/:ro
      - ermis-static-assets:/var/ermis-server/
      - ./certs:/etc/ermis-server/certs:ro
    depends_on:
      - ermis-server
    restart: unless-stopped

networks:
  ermis-net:
    driver: bridge

secrets:
  db_user_password:
    file: ./secrets/db_user_password
  keystore_password:
    file: ./secrets/keystore_password
  emailer_password:
    file: ./secrets/emailer_password

volumes:
  ermis-user-files:
  ermis-static-assets:
  ermis-postgres-data:
