name: Detect Changed Modules

permissions:
  contents: read

on:
  workflow_call:
    outputs:
      server:
        value: ${{ jobs.detect-changes.outputs.server }}
      common:
        value: ${{ jobs.detect-changes.outputs.common }}
      desktop-client:
        value: ${{ jobs.detect-changes.outputs.desktop-client }}
      ermis-client:
        value: ${{ jobs.detect-changes.outputs.ermis-client }}

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    outputs:
      server: ${{ steps.filter.outputs.server }}
      common: ${{ steps.filter.outputs.common }}
      desktop-client: ${{ steps.filter.outputs.desktop-client }}
      ermis-client: ${{ steps.filter.outputs.ermis-client }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            server:
              - 'ErmisServer/**'
            common:
              - 'ErmisCommon/**'
            desktop-client:
              - 'ErmisClient/Desktop/**'
            ermis-client:
              - 'ErmisClient/Mobile/**'

