name: Detect Changed Modules

permissions:
  contents: read

on:
  workflow_call:
    outputs:
      server:
        value: ${{ jobs.detect-changes.outputs.server }}
      common:
        value: ${{ jobs.detect-changes.outputs.common }}
      desktop-client:
        value: ${{ jobs.detect-changes.outputs.desktop-client }}
      ermis-client:
        value: ${{ jobs.detect-changes.outputs.ermis-client }}

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    outputs:
      server: ${{ steps.filter.outputs.server }}
      common: ${{ steps.filter.outputs.common }}
      desktop-client: ${{ steps.filter.outputs.desktop-client }}
      ermis-client: ${{ steps.filter.outputs.ermis-client }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            server:
              - 'ErmisServer/**'
            common:
              - 'ErmisCommon/**'
            desktop-client:
              - 'ErmisClient/Desktop/**'
            ermis-client:
              - 'ErmisClient/Mobile/**'

