name: Server Release (DEB)

permissions:
  contents: write
  packages: write

on:
  release:
    types: [published]

jobs:
  init:
    if: startsWith(github.ref_name, 'server')
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.server_version }}
      version_mj: ${{ steps.version_mj.outputs.server_version }}
      is_dev: ${{ steps.version.outputs.is_dev }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Parse server version
        id: version
        run: |
          VERSION=${GITHUB_REF_NAME#server-v}
          echo "server_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Extract major & minor server version
        id: version_mj
        run: |
          VERSION=${GITHUB_REF_NAME#server-v}
          MAJOR_MINOR=$(echo "$VERSION" | cut -d. -f1,2)
          echo "server_version=$MAJOR_MINOR" >> $GITHUB_OUTPUT

  release:
    if: success() && startsWith(github.ref_name, 'server')
    needs: [init]
    runs-on: ubuntu-latest
    env:
      SERVER_VERSION_FULL: ${{ needs.init.outputs.version }}
      SERVER_VERSION_MJ: ${{ needs.init.outputs.version_mj}}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK 21
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.7.0
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build Debian-based Installer
        run: |
          mvn package -DskipTests
          cd ErmisServer/Installers/Unix/DEB
          chmod +x build_debian_installer.sh
          SERVER_VERSION=$SERVER_VERSION_FULL ./build_debian_installer.sh

      - name: Substitute version placeholders with proper version
        run: |
          export SERVER_VERSION=$SERVER_VERSION_MJ
          # Substitute version placeholder with actual version in compose file
          envsubst < ErmisServer/docker-compose.yml > docker-compose.yml
          mv docker-compose.yml ErmisServer/docker-compose.yml
          mkdir temp/
          for f in ErmisServer/Docker/bootstrap/*.*; do
            envsubst < "$f" > temp/${f##*/}
          done
          mv temp/*.* ErmisServer/Docker/bootstrap/

      - name: Build Docker ZIP
        run: |
          tar -czf ermis-docker-$SERVER_VERSION_FULL.tar.gz \
            --transform='s|.*/||' \
            ErmisServer/docker-compose.yml \
            ErmisServer/Docker/bootstrap/*

      - name: Upload Artifacts to Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: |
            ErmisServer/Installers/Unix/DEB/ermis-server-installer_all.deb
            ermis-docker-$SERVER_VERSION_FULL.tar.gz

      # Release Docker image
      - name: Set up QEMU
        uses: docker/setup-qemu-action@7f9aaaffa50b7aa9d8d6f147ed9a1be21f255d98 # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v3.7.1

      - name: Login to DockerHub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Shorten git SHA to just 7 chars (full SHA is 40 chars)
      - name: Set short SHA
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Extract lowercase repo owner name
        id: owner
        run: echo "lowercase=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      # Push Docker image to DockerHub & GHCR
      - name: Build image and push to registries
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: .
          file: ErmisServer/Docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          # Enable caching inside GitHub Actions to speed up subsequent builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/ermis-server:stable
            ${{ secrets.DOCKER_HUB_USERNAME }}/ermis-server:$SERVER_VERSION_FULL
            ${{ secrets.DOCKER_HUB_USERNAME }}/ermis-server:$SERVER_VERSION_MJ
            ${{ secrets.DOCKER_HUB_USERNAME }}/ermis-server:${{ steps.sha.outputs.sha_short }}
            ghcr.io/${{ steps.owner.outputs.lowercase }}/ermis-server:stable
            ghcr.io/${{ steps.owner.outputs.lowercase }}/ermis-server:$SERVER_VERSION_FULL
            ghcr.io/${{ steps.owner.outputs.lowercase }}/ermis-server:$SERVER_VERSION_MJ
            ghcr.io/${{ steps.owner.outputs.lowercase }}/ermis-server:${{ steps.sha.outputs.sha_short }}
