name: SonarQube
permissions:
  contents: read
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  detect-module-changes:
    uses: ./.github/workflows/detect-changed-modules.yml

  server:
    name: Analyze Server
    needs: detect-module-changes
    if: needs.detect-module-changes.outputs.server == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      - name: Cache SonarQube packages
        uses: actions/cache@v6.1.0
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Set up JDK
        uses: actions/setup-java@v5.5.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v6.1.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Test
        run: |
          mvn verify

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Koukobin_Ermis
            -Dsonar.organization=koukobin
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=ErmisServer/src/main,ErmisCommon/src/main,
            -Dsonar.tests=ErmisServer/src/test,ErmisCommon/src/test
            -Dsonar.java.binaries=ErmisServer/target/classes,ErmisCommon/target/classes

  desktop_client:
    name: Analyze Desktop Client
    needs: detect-module-changes
    if: needs.detect-module-changes.outputs.desktop-client == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      - name: Cache SonarQube packages
        uses: actions/cache@v6.1.0
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Set up JDK
        uses: actions/setup-java@v5.5.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v6.1.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Test
        run: |
          mvn verify

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Koukobin_Ermis
            -Dsonar.organization=koukobin
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=ErmisClient/Desktop/src/main,ErmisCommon/src/main,
            -Dsonar.tests=ErmisClient/Desktop/src/test,ErmisCommon/src/test
            -Dsonar.java.binaries=ErmisServer/target/classes,ErmisCommon/target/classes


  ermis_client:
    name: Analyze Mobile Client
    needs: detect-module-changes
    if: needs.detect-module-changes.outputs.ermis-client == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      - name: Cache SonarQube packages
        uses: actions/cache@v6.1.0
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.1'

      - name: Analyze Mobile Client
        working-directory: ErmisClient/Mobile/ermis_client
        run: |
          chmod +x build.sh
          ./build.sh
          flutter analyze --write=analysis-report.txt || true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Koukobin_Ermis
            -Dsonar.organization=koukobin
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=ErmisClient/Mobile/ermis_client/lib
            -Dsonar.dart.analyzer.report.path=ErmisClient/Mobile/ermis_client/analysis-report.txt
            -Dsonar.java.binaries=ErmisClient/Desktop/target/classes,ErmisCommon/target/classes


