stream {
    upstream http_backend {
        server 127.0.0.1:8443;  # internal nginx HTTPS for static files
    }

    upstream tcp_backend {
        server IP_ADDRESS:SERVER_PORT;  # reverse proxy to ermis-server backend
    }

    map $ssl_preread_alpn_protocols $backend {
        ~\bhttp/1.1\b  http_backend;
        ~\bh2\b        http_backend;
        default        tcp_backend;
    }

    server {
        listen 443;
        ssl_preread on;
        proxy_pass $backend;
        proxy_ssl off;
    }

    server {
        listen 80;
        ssl_preread on;
        proxy_pass $backend;
        proxy_ssl off;
    }
}

